/*
 * Copyright (c) 2022 hpmicro
 *
 * SPDX-License-Identifier: Apache-2.0
 *
 */

#ifndef ZEPHYR_INCLUDE_DT_BINDINGS_PINCTRL_HPMICRO_PINCTRL_COMMON_H_
#define ZEPHYR_INCLUDE_DT_BINDINGS_PINCTRL_HPMICRO_PINCTRL_COMMON_H_

#include <zephyr/sys/util_macro.h>

#define HPMICRO_PIN_NUM_SHIFT      0U
#define HPMICRO_PIN_NUM_MASK       0x3FFU


#define HPMICRO_PIN_ANALOG_MASK      1U
#define HPMICRO_PIN_ANALOG_SHIFT     10U
#define HPMICRO_PIN_ALT_MASK         0x1FU
#define HPMICRO_PIN_ALT_SHIFT        11U

#define HPMICRO_PINMUX(pin, is_analog, alt)						\
		(((pin & HPMICRO_PIN_NUM_MASK) << HPMICRO_PIN_NUM_SHIFT) |		\
		((is_analog & HPMICRO_PIN_ANALOG_MASK) << HPMICRO_PIN_ANALOG_SHIFT) |	\
		((alt & HPMICRO_PIN_ALT_MASK) << HPMICRO_PIN_ALT_SHIFT))

#define HPMICRO_OPEN_DRAIN			1U
#define HPMICRO_OPEN_DRAIN_SHIFT	0U

#define HPMICRO_NO_PULL				1U
#define HPMICRO_NO_PULL_SHIFT		1U

#define HPMICRO_PULL_DOWN			1U
#define HPMICRO_PULL_DOWN_SHIFT		2U

#define HPMICRO_PULL_UP				1U
#define HPMICRO_PULL_UP_SHIFT		3U

#define HPMICRO_FORCE_INPUT				1U
#define HPMICRO_FORCE_INPUT_SHIFT		4U

#define HPMICRO_DRIVER_STRENGTH				7U
#define HPMICRO_DRIVER_STRENGTH_SHIFT		5U

#define HPMICRO_SCHMITT_ENABLE				1U
#define HPMICRO_SCHMITT_ENABLE_SHIFT		12U

#define HPMICRO_POWER			1U
#define HPMICRO_POWER_SHIFT		13U

#endif	/* ZEPHYR_INCLUDE_DT_BINDINGS_PINCTRL_HPMICRO_PINCTRL_COMMON_H_ */
